# Generated by Django 5.0.6 on 2024-07-02 08:04

import django.db.models.deletion
import tournaments.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('round_number', models.IntegerField(default=0)),
                ('current_round', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('round', models.IntegerField(default=0)),
                ('table', models.IntegerField(default=0)),
                ('player1_wins', models.IntegerField(default=0)),
                ('player2_win', models.IntegerField(default=0)),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player1', to='tournaments.player')),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player2', to='tournaments.player')),
                ('tournament', models.ForeignKey(default=tournaments.models.Tournament.get_default_pk, on_delete=django.db.models.deletion.CASCADE, to='tournaments.tournament')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_on', models.DateTimeField(auto_now_add=True)),
                ('score', models.IntegerField(default=0)),
                ('games_played', models.IntegerField(default=0)),
                ('games_won', models.IntegerField(default=0)),
                ('pmw', models.FloatField(default=0)),
                ('omw', models.FloatField(default=0)),
                ('pgw', models.FloatField(default=0)),
                ('ogw', models.FloatField(default=0)),
                ('paired', models.BooleanField(default=False)),
                ('had_bye', models.BooleanField(default=False)),
                ('judge_note', models.CharField(blank=True, max_length=450)),
                ('pairings', models.ManyToManyField(blank=True, to='tournaments.enrollment')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.player')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.tournament')),
            ],
            options={
                'unique_together': {('player', 'tournament')},
            },
        ),
    ]
