# Generated by Django 5.0.6 on 2024-07-15 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_enrollment_seat'),
    ]

    operations = [
        migrations.AddField(
            model_name='draft',
            name='seated',
            field=models.BooleanField(default=False),
        ),
    ]
