# Generated by Django 5.0.6 on 2024-07-03 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_tournament_end_datetime_tournament_start_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='player2_win',
            new_name='player2_wins',
        ),
        migrations.AlterField(
            model_name='game',
            name='player1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player1', to='tournaments.enrollment'),
        ),
        migrations.AlterField(
            model_name='game',
            name='player2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player2', to='tournaments.enrollment'),
        ),
    ]
