# Generated by Django 5.0.6 on 2024-07-15 10:30

from django.db import migrations, models


class Migration(migrations.Migration):
  dependencies = [
    ("tournaments", "0003_draft_seated"),
  ]

  operations = [
    migrations.RemoveField(
      model_name="round",
      name="round_length",
    ),
    migrations.RemoveField(
      model_name="round",
      name="round_timer_start",
    ),
    migrations.AddField(
      model_name="round",
      name="started",
      field=models.BooleanField(default=False),
    ),
  ]
