# Generated by Django 5.0.6 on 2024-07-03 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_rename_player2_win_game_player2_wins_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='round_length',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='tournament',
            name='round_timer_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
