# Generated by Django 5.0.6 on 2024-07-03 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0004_tournament_round_length_tournament_round_timer_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='timer_active',
            field=models.BooleanField(default=False),
        ),
    ]
