# Generated by Django 5.0.6 on 2024-07-03 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0005_tournament_timer_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='timer_active',
        ),
    ]
