# Generated by Django 5.0.6 on 2024-07-16 16:21

import tournaments.models
from django.db import migrations, models


class Migration(migrations.Migration):
  dependencies = [
    ("tournaments", "0008_image"),
  ]

  operations = [
    migrations.AddField(
      model_name="enrollment",
      name="checked_in",
      field=models.BooleanField(default=False),
    ),
    migrations.AddField(
      model_name="enrollment",
      name="checked_out",
      field=models.BooleanField(default=False),
    ),
    migrations.AlterField(
      model_name="image",
      name="image",
      field=models.ImageField(upload_to=tournaments.models.user_directory_path),
    ),
  ]
