# Generated by Django 5.0.6 on 2024-07-16 16:22

from django.db import migrations, models


class Migration(migrations.Migration):
  dependencies = [
    ("tournaments", "0009_enrollment_checked_in_enrollment_checked_out_and_more"),
  ]

  operations = [
    migrations.AddField(
      model_name="image",
      name="draft",
      field=models.IntegerField(default=0),
    ),
  ]
