# Generated by Django 5.0.6 on 2024-07-10 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0009_game_result_reported_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='group',
            field=models.ManyToManyField(blank=True, to='tournaments.enrollment'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='seating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tournament',
            name='is_event',
            field=models.BooleanField(default=True),
        ),
    ]
