# Generated by Django 5.0.6 on 2024-07-16 16:22

from django.db import migrations


class Migration(migrations.Migration):
  dependencies = [
    ("tournaments", "0010_image_draft"),
  ]

  operations = [
    migrations.RenameField(
      model_name="image",
      old_name="draft",
      new_name="draft_idx",
    ),
  ]
