# Generated by Django 5.0.6 on 2024-07-10 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0010_enrollment_group_enrollment_seating_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('tournament_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tournaments.tournament')),
            ],
            bases=('tournaments.tournament',),
        ),
    ]
