# Generated by Django 5.0.6 on 2024-07-10 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0012_remove_tournament_is_event_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='phase',
            unique_together={('event', 'phase_idx')},
        ),
    ]
