# Generated by Django 5.0.6 on 2024-07-10 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0013_alter_phase_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cube',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('url', models.URLField()),
            ],
        ),
        migrations.RenameField(
            model_name='phase',
            old_name='event',
            new_name='tournament',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='group',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='seating',
        ),
        migrations.RemoveField(
            model_name='game',
            name='tournament',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='current_round',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='round_number',
        ),
        migrations.AlterUniqueTogether(
            name='phase',
            unique_together={('tournament', 'phase_idx')},
        ),
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('round_number', models.IntegerField(default=3)),
                ('cube', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.cube')),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.phase')),
            ],
            options={
                'unique_together': {('phase', 'cube')},
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.draft')),
                ('enrollments', models.ManyToManyField(to='tournaments.enrollment')),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('round_idx', models.IntegerField(default=0)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.draft')),
            ],
            options={
                'unique_together': {('draft', 'round_idx')},
            },
        ),
        migrations.AlterField(
            model_name='game',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.round'),
        ),
    ]
