# Generated by Django 5.0.6 on 2024-07-10 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0014_cube_rename_event_phase_tournament_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phase',
            old_name='phase_idx',
            new_name='phase_index',
        ),
        migrations.AlterUniqueTogether(
            name='phase',
            unique_together={('tournament', 'phase_index')},
        ),
    ]
