# Generated by Django 5.0.6 on 2024-07-10 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0015_rename_phase_idx_phase_phase_index_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phase',
            old_name='phase_index',
            new_name='phase_idx',
        ),
        migrations.AlterUniqueTogether(
            name='phase',
            unique_together={('tournament', 'phase_idx')},
        ),
        migrations.AlterField(
            model_name='phase',
            name='current_round',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='phase',
            name='round_length',
            field=models.IntegerField(default=50, verbose_name='Round length in minutes'),
        ),
        migrations.AlterField(
            model_name='phase',
            name='round_number',
            field=models.IntegerField(default=3, verbose_name='Amount of rounds'),
        ),
        migrations.AlterField(
            model_name='round',
            name='round_idx',
            field=models.IntegerField(default=1, verbose_name='Round number'),
        )
    ]
