# Generated by Django 5.0.6 on 2024-07-10 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0016_alter_phase_unique_together_phase_phase_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phase',
            name='round_length',
        ),
        migrations.RemoveField(
            model_name='phase',
            name='round_timer_start',
        ),
        migrations.AddField(
            model_name='round',
            name='round_length',
            field=models.IntegerField(default=50, verbose_name='Round length in minutes'),
        ),
        migrations.AddField(
            model_name='round',
            name='round_timer_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='draft',
            name='round_number',
            field=models.IntegerField(default=3, verbose_name='Amount of rounds'),
        ),
        migrations.AlterField(
            model_name='phase',
            name='phase_idx',
            field=models.IntegerField(default=1, verbose_name='Phase Number'),
        ),
    ]
