# Generated by Django 5.0.6 on 2024-07-10 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0017_remove_phase_round_length_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cube',
            name='description',
            field=models.CharField(default='sample description', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cube',
            name='url',
            field=models.URLField(unique=True, verbose_name='URL'),
        ),
    ]
