# Generated by Django 5.0.6 on 2024-07-21 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0017_image_checkin'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='bye_this_round',
            field=models.BooleanField(default=False),
        ),
    ]
