# Generated by Django 5.0.6 on 2024-07-10 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0018_cube_description_alter_cube_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='draft',
        ),
    ]
