# Generated by Django 5.0.6 on 2024-07-23 10:02

from django.db import migrations


class Migration(migrations.Migration):
  dependencies = [
    ("tournaments", "0018_enrollment_bye_this_round"),
  ]

  operations = [
    migrations.RemoveField(
      model_name="player",
      name="name",
    ),
  ]
