# Generated by Django 5.0.6 on 2024-07-10 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0019_remove_group_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='draft',
            name='enrollments',
            field=models.ManyToManyField(to='tournaments.enrollment'),
        ),
    ]
