# Generated by Django 5.0.6 on 2024-07-11 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0020_draft_enrollments'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
