# Generated by Django 5.0.6 on 2024-07-23 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0020_player_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
