# Generated by Django 5.0.6 on 2024-07-12 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0021_round_finished'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Group',
        ),
    ]
