# Generated by Django 5.0.7 on 2024-07-26 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
  dependencies = [
    ("tournaments", "0023_phase_is_sideevent_delete_sideevent"),
  ]

  operations = [
    migrations.RemoveField(
      model_name="phase",
      name="is_sideevent",
    ),
    migrations.CreateModel(
      name="SideEvent",
      fields=[
        (
          "tournament_ptr",
          models.OneToOneField(
            auto_created=True,
            on_delete=django.db.models.deletion.CASCADE,
            parent_link=True,
            primary_key=True,
            serialize=False,
            to="tournaments.tournament",
          ),
        ),
        ("description", models.CharField(blank=True, max_length=255)),
        (
          "tournament",
          models.ForeignKey(
            on_delete=django.db.models.deletion.CASCADE,
            related_name="side_events",
            to="tournaments.tournament",
          ),
        ),
      ],
      bases=("tournaments.tournament",),
    ),
  ]
