# Generated by Django 5.0.7 on 2024-07-27 13:44

from django.db import migrations, models


class Migration(migrations.Migration):
  dependencies = [
    ("tournaments", "0026_phase_started"),
  ]

  operations = [
    migrations.AddField(
      model_name="draft",
      name="slug",
      field=models.SlugField(null=True),
    ),
    migrations.AddField(
      model_name="tournament",
      name="slug",
      field=models.SlugField(null=True),
    ),
  ]
