# Generated by Django 5.0.7 on 2024-07-27 20:37

from django.db import migrations, models


class Migration(migrations.Migration):
  dependencies = [
    ("tournaments", "0028_tournament_current_round"),
  ]

  operations = [
    migrations.AlterField(
      model_name="draft",
      name="slug",
      field=models.SlugField(unique=True),
    ),
    migrations.AlterField(
      model_name="tournament",
      name="slug",
      field=models.SlugField(unique=True),
    ),
  ]
