# Generated by Django 5.0.7 on 2024-07-30 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0030_remove_sideevent_description_tournament_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='player_capacity',
            field=models.IntegerField(default=0),
        ),
    ]
