# Generated by Django 5.0.7 on 2024-07-30 11:18

from django.db import migrations, models


class Migration(migrations.Migration):
  dependencies = [
    ("tournaments", "0031_tournament_player_capacity"),
  ]

  operations = [
    migrations.AddField(
      model_name="tournament",
      name="signed_up",
      field=models.IntegerField(default=0),
    ),
  ]
