# Generated by Django 5.0.7 on 2024-07-31 08:43

from django.db import migrations, models


class Migration(migrations.Migration):
  dependencies = [
    ("tournaments", "0032_tournament_signed_up"),
  ]

  operations = [
    migrations.AddField(
      model_name="cube",
      name="image",
      field=models.ImageField(blank=True, upload_to=""),
    ),
  ]
