# Generated by Django 5.0.7 on 2024-07-31 08:47

import tournaments.models
from django.db import migrations, models


class Migration(migrations.Migration):
  dependencies = [
    ("tournaments", "0033_cube_image"),
  ]

  operations = [
    migrations.AlterField(
      model_name="cube",
      name="image",
      field=models.ImageField(
        blank=True, upload_to=tournaments.models.cube_directory_path
      ),
    ),
  ]
