# Generated by Django 5.0.7 on 2024-07-31 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0034_alter_cube_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cube',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
