# Generated by Django 5.0.7 on 2024-07-31 09:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
  dependencies = [
    ("tournaments", "0035_cube_slug"),
    migrations.swappable_dependency(settings.AUTH_USER_MODEL),
  ]

  operations = [
    migrations.AddField(
      model_name="cube",
      name="creator",
      field=models.ForeignKey(
        null=True,
        on_delete=django.db.models.deletion.CASCADE,
        to=settings.AUTH_USER_MODEL,
      ),
    ),
  ]
