# Generated by Django 5.0.7 on 2024-07-31 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0036_cube_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='cube',
            name='card_number',
            field=models.IntegerField(default=0),
        ),
    ]
