# Generated by Django 5.0.7 on 2024-07-31 09:04

from django.db import migrations, models


class Migration(migrations.Migration):
  dependencies = [
    ("tournaments", "0037_cube_card_number"),
  ]

  operations = [
    migrations.AddField(
      model_name="cube",
      name="special_rules",
      field=models.TextField(blank=True),
    ),
  ]
