# Generated by Django 5.0.7 on 2024-07-31 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0038_cube_special_rules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cube',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
