# Generated by Django 5.0.7 on 2024-08-01 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0039_alter_cube_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='draft_place',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='tournament_place',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
