# Generated by Django 5.0.7 on 2024-08-01 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0040_enrollment_draft_place_enrollment_tournament_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
