# Generated by Django 5.0.7 on 2024-08-06 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0042_enrollment_dropped'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='draft',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tournaments.draft'),
        ),
    ]
