# Generated by Django 5.0.7 on 2024-08-10 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0045_draft_first_table_draft_last_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='announcement',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
